# Generated by Django 5.0.7 on 2024-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.IntegerField()),
                ('member_name', models.CharField(max_length=35)),
                ('member_address', models.CharField(max_length=70)),
            ],
        ),
    ]
