use vipuldb;
show tables;
select * from soc1_app_acc_group;
select * from soc1_app_account_head;
DELETE FROM soc1_app_loan_repayment_sch where loan_ac_no_srno>=800015001;
select * from soc1_app_loan_repayment_sch;
UPDATE  soc1_app_int_cal_controll SET vch_no=3000000 WHERE yrmn = 202411;
DELETE FROM soc1_app_int_cal_controll where yrmn=202412;
select * from soc1_app_mem_share_detail;
DELETE FROM  soc1_app_mem_share_detail where share_srno>=900001;
select * from soc1_app_vch_control_srno;
UPDATE   soc1_app_vch_control SET st_no=1000000 WHERE tr_type=1;
UPDATE   soc1_app_vch_control SET st_no=2000000 WHERE tr_type=2;
UPDATE   soc1_app_vch_control SET st_no=800000 WHERE tr_type=8;
UPDATE   soc1_app_vch_control SET st_no=900000 WHERE tr_type=9;
select * from soc1_app_vch_control_srno;
DELETE FROM soc1_app_vch_control_srno where st_no>=100000;
select * from soc1_app_vch_trans;
DELETE FROM soc1_app_vch_trans where vch_no>=1;
select * from soc1_app_vch_type;